package com.itfaculty.progress.model;
// Generated Feb 3, 2017 11:29:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Docappoinments generated by hbm2java
 */
@Entity
@Table(name="docappoinments"
    ,catalog="nawalokahospital"
)
public class Docappoinments  implements java.io.Serializable {


     private Integer docappoinmentsId;
     private Doctors doctors;
     private Date doctorAvailabletime;

    public Docappoinments() {
    }

    public Docappoinments(Doctors doctors, Date doctorAvailabletime) {
       this.doctors = doctors;
       this.doctorAvailabletime = doctorAvailabletime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="docappoinments_id", unique=true, nullable=false)
    public Integer getDocappoinmentsId() {
        return this.docappoinmentsId;
    }
    
    public void setDocappoinmentsId(Integer docappoinmentsId) {
        this.docappoinmentsId = docappoinmentsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doctors_doctor_id", nullable=false)
    public Doctors getDoctors() {
        return this.doctors;
    }
    
    public void setDoctors(Doctors doctors) {
        this.doctors = doctors;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="doctor_availabletime", nullable=false, length=19)
    public Date getDoctorAvailabletime() {
        return this.doctorAvailabletime;
    }
    
    public void setDoctorAvailabletime(Date doctorAvailabletime) {
        this.doctorAvailabletime = doctorAvailabletime;
    }




}


