package com.itfaculty.progress.model;
// Generated Feb 3, 2017 11:29:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Doctors generated by hbm2java
 */
@Entity
@Table(name="doctors"
    ,catalog="nawalokahospital"
    , uniqueConstraints = @UniqueConstraint(columnNames="doctor_username") 
)
public class Doctors  implements java.io.Serializable {


     private Integer doctorId;
     private String doctorFirstname;
     private String doctorLastname;
     private String doctorUsername;
     private String doctorPassword;
     private String doctorTelno;
     private Set<Docappoinments> docappoinmentses = new HashSet<Docappoinments>(0);
     private Set<Records> recordses = new HashSet<Records>(0);

    public Doctors() {
    }

	
    public Doctors(String doctorFirstname, String doctorLastname, String doctorUsername, String doctorPassword, String doctorTelno) {
        this.doctorFirstname = doctorFirstname;
        this.doctorLastname = doctorLastname;
        this.doctorUsername = doctorUsername;
        this.doctorPassword = doctorPassword;
        this.doctorTelno = doctorTelno;
    }
    public Doctors(String doctorFirstname, String doctorLastname, String doctorUsername, String doctorPassword, String doctorTelno, Set<Docappoinments> docappoinmentses, Set<Records> recordses) {
       this.doctorFirstname = doctorFirstname;
       this.doctorLastname = doctorLastname;
       this.doctorUsername = doctorUsername;
       this.doctorPassword = doctorPassword;
       this.doctorTelno = doctorTelno;
       this.docappoinmentses = docappoinmentses;
       this.recordses = recordses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="doctor_id", unique=true, nullable=false)
    public Integer getDoctorId() {
        return this.doctorId;
    }
    
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    
    @Column(name="doctor_firstname", nullable=false, length=100)
    public String getDoctorFirstname() {
        return this.doctorFirstname;
    }
    
    public void setDoctorFirstname(String doctorFirstname) {
        this.doctorFirstname = doctorFirstname;
    }

    
    @Column(name="doctor_lastname", nullable=false, length=100)
    public String getDoctorLastname() {
        return this.doctorLastname;
    }
    
    public void setDoctorLastname(String doctorLastname) {
        this.doctorLastname = doctorLastname;
    }

    
    @Column(name="doctor_username", unique=true, nullable=false, length=100)
    public String getDoctorUsername() {
        return this.doctorUsername;
    }
    
    public void setDoctorUsername(String doctorUsername) {
        this.doctorUsername = doctorUsername;
    }

    
    @Column(name="doctor_password", nullable=false)
    public String getDoctorPassword() {
        return this.doctorPassword;
    }
    
    public void setDoctorPassword(String doctorPassword) {
        this.doctorPassword = doctorPassword;
    }

    
    @Column(name="doctor_telno", nullable=false, length=100)
    public String getDoctorTelno() {
        return this.doctorTelno;
    }
    
    public void setDoctorTelno(String doctorTelno) {
        this.doctorTelno = doctorTelno;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doctors")
    public Set<Docappoinments> getDocappoinmentses() {
        return this.docappoinmentses;
    }
    
    public void setDocappoinmentses(Set<Docappoinments> docappoinmentses) {
        this.docappoinmentses = docappoinmentses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="doctors")
    public Set<Records> getRecordses() {
        return this.recordses;
    }
    
    public void setRecordses(Set<Records> recordses) {
        this.recordses = recordses;
    }




}


