package com.itfaculty.progress.model;
// Generated Feb 3, 2017 11:29:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Labassistants generated by hbm2java
 */
@Entity
@Table(name="labassistants"
    ,catalog="nawalokahospital"
)
public class Labassistants  implements java.io.Serializable {


     private Integer labassistantId;
     private String labassistantFirstname;
     private String labassistantLastname;
     private String labassistantUsername;
     private String labassistantPassword;
     private Set<Records> recordses = new HashSet<Records>(0);

    public Labassistants() {
    }

	
    public Labassistants(String labassistantFirstname, String labassistantLastname, String labassistantUsername, String labassistantPassword) {
        this.labassistantFirstname = labassistantFirstname;
        this.labassistantLastname = labassistantLastname;
        this.labassistantUsername = labassistantUsername;
        this.labassistantPassword = labassistantPassword;
    }
    public Labassistants(String labassistantFirstname, String labassistantLastname, String labassistantUsername, String labassistantPassword, Set<Records> recordses) {
       this.labassistantFirstname = labassistantFirstname;
       this.labassistantLastname = labassistantLastname;
       this.labassistantUsername = labassistantUsername;
       this.labassistantPassword = labassistantPassword;
       this.recordses = recordses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="labassistant_id", unique=true, nullable=false)
    public Integer getLabassistantId() {
        return this.labassistantId;
    }
    
    public void setLabassistantId(Integer labassistantId) {
        this.labassistantId = labassistantId;
    }

    
    @Column(name="labassistant_firstname", nullable=false, length=100)
    public String getLabassistantFirstname() {
        return this.labassistantFirstname;
    }
    
    public void setLabassistantFirstname(String labassistantFirstname) {
        this.labassistantFirstname = labassistantFirstname;
    }

    
    @Column(name="labassistant_lastname", nullable=false, length=100)
    public String getLabassistantLastname() {
        return this.labassistantLastname;
    }
    
    public void setLabassistantLastname(String labassistantLastname) {
        this.labassistantLastname = labassistantLastname;
    }

    
    @Column(name="labassistant_username", nullable=false, length=100)
    public String getLabassistantUsername() {
        return this.labassistantUsername;
    }
    
    public void setLabassistantUsername(String labassistantUsername) {
        this.labassistantUsername = labassistantUsername;
    }

    
    @Column(name="labassistant_password", nullable=false)
    public String getLabassistantPassword() {
        return this.labassistantPassword;
    }
    
    public void setLabassistantPassword(String labassistantPassword) {
        this.labassistantPassword = labassistantPassword;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="labassistants")
    public Set<Records> getRecordses() {
        return this.recordses;
    }
    
    public void setRecordses(Set<Records> recordses) {
        this.recordses = recordses;
    }




}


