package com.itfaculty.progress.model;
// Generated Feb 3, 2017 11:29:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Records generated by hbm2java
 */
@Entity
@Table(name="records"
    ,catalog="nawalokahospital"
)
public class Records  implements java.io.Serializable {


     private Integer recordId;
     private Doctors doctors;
     private Labassistants labassistants;
     private Patients patients;
     private String recordNameofmedicine;
     private String recordFrequency;
     private String recordCondition;
     private String recordPhysician;
     private String recordImage;
     private String recordResultPrescription;
     private Date recordCreatedDate;

    public Records() {
    }

    public Records(Doctors doctors, Labassistants labassistants, Patients patients, String recordNameofmedicine, String recordFrequency, String recordCondition, String recordPhysician, String recordImage, String recordResultPrescription, Date recordCreatedDate) {
       this.doctors = doctors;
       this.labassistants = labassistants;
       this.patients = patients;
       this.recordNameofmedicine = recordNameofmedicine;
       this.recordFrequency = recordFrequency;
       this.recordCondition = recordCondition;
       this.recordPhysician = recordPhysician;
       this.recordImage = recordImage;
       this.recordResultPrescription = recordResultPrescription;
       this.recordCreatedDate = recordCreatedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="record_id", unique=true, nullable=false)
    public Integer getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doctors_doctor_id", nullable=false)
    public Doctors getDoctors() {
        return this.doctors;
    }
    
    public void setDoctors(Doctors doctors) {
        this.doctors = doctors;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="labassistants_labassistant_id", nullable=false)
    public Labassistants getLabassistants() {
        return this.labassistants;
    }
    
    public void setLabassistants(Labassistants labassistants) {
        this.labassistants = labassistants;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patients_patient_id", nullable=false)
    public Patients getPatients() {
        return this.patients;
    }
    
    public void setPatients(Patients patients) {
        this.patients = patients;
    }

    
    @Column(name="record_nameofmedicine", nullable=false)
    public String getRecordNameofmedicine() {
        return this.recordNameofmedicine;
    }
    
    public void setRecordNameofmedicine(String recordNameofmedicine) {
        this.recordNameofmedicine = recordNameofmedicine;
    }

    
    @Column(name="record_frequency", nullable=false)
    public String getRecordFrequency() {
        return this.recordFrequency;
    }
    
    public void setRecordFrequency(String recordFrequency) {
        this.recordFrequency = recordFrequency;
    }

    
    @Column(name="record_condition", nullable=false)
    public String getRecordCondition() {
        return this.recordCondition;
    }
    
    public void setRecordCondition(String recordCondition) {
        this.recordCondition = recordCondition;
    }

    
    @Column(name="record_physician", nullable=false)
    public String getRecordPhysician() {
        return this.recordPhysician;
    }
    
    public void setRecordPhysician(String recordPhysician) {
        this.recordPhysician = recordPhysician;
    }

    
    @Column(name="record_image", nullable=false)
    public String getRecordImage() {
        return this.recordImage;
    }
    
    public void setRecordImage(String recordImage) {
        this.recordImage = recordImage;
    }

    
    @Column(name="record_result_prescription", nullable=false)
    public String getRecordResultPrescription() {
        return this.recordResultPrescription;
    }
    
    public void setRecordResultPrescription(String recordResultPrescription) {
        this.recordResultPrescription = recordResultPrescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="record_created_date", nullable=false, length=19)
    public Date getRecordCreatedDate() {
        return this.recordCreatedDate;
    }
    
    public void setRecordCreatedDate(Date recordCreatedDate) {
        this.recordCreatedDate = recordCreatedDate;
    }




}


